# Generated by hand to mirror `rextendr::document()` output.
# The `wrap__read_sas7bdat` symbol is emitted by the `#[extendr]` macro.
#
# Named `sas7bdat_read_impl` rather than `read_sas7bdat` so the exported R
# function can take that name: it is the one spelling that does not collide with
# `haven::read_sas()`.

#' @useDynLib fastsas, .registration = TRUE
#' @keywords internal
NULL

sas7bdat_read_impl <- function(path, catalog, categorical, io_backend, threads) .Call("wrap__read_sas7bdat", path, catalog, categorical, io_backend, threads, PACKAGE = "fastsas")
