# Generated by hand to mirror `rextendr::document()` output.
# The `wrap__read_sas7bdat` symbol is emitted by the `#[extendr]` macro.

#' @useDynLib fastsas, .registration = TRUE
#' @keywords internal
NULL

read_sas7bdat <- function(path, catalog, categorical) .Call("wrap__read_sas7bdat", path, catalog, categorical, PACKAGE = "fastsas")
