# Generated by hand to mirror `rextendr::document()` output.
# The `wrap__read_sas7bdat` symbol is emitted by the `#[extendr]` macro.

#' @useDynLib readsas, .registration = TRUE
#' @keywords internal
NULL

read_sas7bdat <- function(path, catalog) .Call("wrap__read_sas7bdat", path, catalog, PACKAGE = "readsas")
