# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib SASreaderRUST, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_SASreaderRUST__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_SASreaderRUST__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`hello` <- function() {
  invisible(.Call(savvy_hello__impl))
}

#' Multiply Input By Another Input
#'
#' @param x An integer vector.
#' @param y An integer to multiply.
#' @returns An integer vector with values multiplied by `y`.
#' @export
`int_times_int` <- function(`x`, `y`) {
  .Call(savvy_int_times_int__impl, `x`, `y`)
}

#' Read a SAS7BDAT file into a column-oriented representation
#'
#' @param path Path to a .sas7bdat file
#' @return Named list of vectors, with column metadata attached as attributes
#' @export
`read_sas` <- function(`path`) {
  .Call(savvy_read_sas__impl, `path`)
}

#' Column names of a SAS7BDAT file
#'
#' @param path Path to a .sas7bdat file
#' @return Character vector of column names
#' @export
`sas_column_names` <- function(`path`) {
  .Call(savvy_sas_column_names__impl, `path`)
}

#' Basic metadata as JSON (for convenient consumption in R)
#'
#' @param path Path to a .sas7bdat file
#' @return Length-1 character vector with a JSON string
#' @export
`sas_metadata_json` <- function(`path`) {
  .Call(savvy_sas_metadata_json__impl, `path`)
}

#' Count rows in a SAS7BDAT file
#'
#' @param path Path to a .sas7bdat file
#' @return Integer scalar with the row count (capped at 2^31-1 if larger)
#' @export
`sas_row_count` <- function(`path`) {
  .Call(savvy_sas_row_count__impl, `path`)
}

#' Convert Input To Upper-Case
#'
#' @param x A character vector.
#' @returns A character vector with upper case version of the input.
#' @export
`to_upper` <- function(`x`) {
  .Call(savvy_to_upper__impl, `x`)
}

#' Stream a SAS7BDAT file into an on-disk sink.
#'
#' @param path Path to the input `.sas7bdat` file.
#' @param sink Output sink identifier (`"parquet"` or `"csv"`).
#' @param output Destination file path for the sink output.
#' @export
`write_sas` <- function(`path`, `sink`, `output`) {
  invisible(.Call(savvy_write_sas__impl, `path`, `sink`, `output`))
}

### wrapper functions for Person

`Person_name` <- function(self) {
  function() {
    .Call(savvy_Person_name__impl, `self`)
  }
}

`Person_set_name` <- function(self) {
  function(`name`) {
    invisible(.Call(savvy_Person_set_name__impl, `self`, `name`))
  }
}

`.savvy_wrap_Person` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`name` <- `Person_name`(ptr)
  e$`set_name` <- `Person_set_name`(ptr)

  class(e) <- c("Person", "savvy_SASreaderRUST__sealed")
  e
}



`Person` <- new.env(parent = emptyenv())

### associated functions for Person

`Person`$`associated_function` <- function() {
  .Call(savvy_Person_associated_function__impl)
}

`Person`$`new` <- function() {
  .savvy_wrap_Person(.Call(savvy_Person_new__impl))
}


class(`Person`) <- c("Person__bundle", "savvy_SASreaderRUST__sealed")

#' @export
`print.Person__bundle` <- function(x, ...) {
  cat('Person\n')
}

