[workspace]
members = [
    "crates/sas7bdat-cli",
    "crates/sas7bdat",
    "crates/polars_plugin",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
arrow-array = "58"
arrow-schema = "58"
bytemuck = { version = "1", features = ["derive"] }
bstr = "1"
criterion = "0.8"
clap = { version = "4", features = ["derive"] }
csv = "1"
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
encoding_rs = "0.8"
glob = "0.3"
hex = "0.4"
hotpath = { version = "0.16", features = ["hotpath"] }
indicatif = "0.18"
memchr = "2.8"
memmap2 = "0.9"
mimalloc = { version = "0.1.49", default-features = false, features = ["secure"] }
num-traits = "0.2"
parquet = { version = "58", features = ["arrow"] }
polars = "0.53"
polars-arrow = "0.53"
polars-plan = { version = "0.53", features = ["serde"] }
pyo3 = { version = "0.27" }
pyo3-polars = "0.26.0"
rayon = "1"
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simdutf8 = "0.1"
walkdir = "2"
tracing = "0.1.44"
tracing-indicatif = "0.3.14"
tracing-subscriber = "0.3.23"

[profile.release]
lto = "thin"
codegen-units = 8
opt-level = 3
panic = "abort"

[profile.dist]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = "symbols"
