pub const SAS_PAGE_TYPE_MASK: u16 = 0x0F00;
pub const SAS_PAGE_TYPE_DATA: u16 = 0x0100;
pub const SAS_PAGE_TYPE_MIX: u16 = 0x0200;
pub const SAS_PAGE_TYPE_COMP: u16 = 0x9000;

pub const SAS_SUBHEADER_SIGNATURE_COLUMN_TEXT: u32 = 0xFFFF_FFFD;
pub const SAS_SUBHEADER_SIGNATURE_COLUMN_ATTRS: u32 = 0xFFFF_FFFC;
pub const SAS_SUBHEADER_SIGNATURE_COLUMN_FORMAT: u32 = 0xFFFF_FBFE;
pub const SAS_SUBHEADER_SIGNATURE_COLUMN_NAME: u32 = 0xFFFF_FFFF;
pub const SAS_SUBHEADER_SIGNATURE_COLUMN_SIZE: u32 = 0xF6F6_F6F6;
pub const SAS_SUBHEADER_SIGNATURE_ROW_SIZE: u32 = 0xF7F7_F7F7;
pub const SAS_SUBHEADER_SIGNATURE_COUNTS: u32 = 0xFFFF_FC00;
pub const SAS_SUBHEADER_SIGNATURE_COLUMN_LIST: u32 = 0xFFFF_FFFE;

pub const SAS_COMPRESSION_NONE: u8 = 0x00;
pub const SAS_COMPRESSION_TRUNC: u8 = 0x01;
pub const SAS_COMPRESSION_ROW: u8 = 0x04;

pub const SUBHEADER_POINTER_OFFSET: usize = 8;
