[package]
name = "sas7bdat-polars"
version = "0.7.1"
edition = "2024"
license = "MIT"
publish = false

[lib]
name = "sas7bdat_polars"
crate-type = ["cdylib", "rlib"]

[dependencies]
arrow-schema = { workspace = true, optional = true }
bytemuck = { workspace = true }
polars = { workspace = true }
polars-arrow = { workspace = true }
polars-plan = { workspace = true }
pyo3 = { workspace = true, features = ["abi3-py312"] }
pyo3-polars = { workspace = true }
rmp-serde = { workspace = true }
sas7bdat = { path = "../sas7bdat", features = ["arrow"] }

[build-dependencies]
pyo3-build-config = { workspace = true }

[features]
default = ["arrow"]
arrow = ["dep:arrow-schema", "sas7bdat/arrow"]
extension-module = ["pyo3/extension-module"]

[lints]
workspace = true
