# Generated by hand to mirror `rextendr::document()` output.
# The `wrap__convert_sas_impl` symbol is emitted by the `#[extendr]` macro.

#' @useDynLib fastsasconvert, .registration = TRUE
#' @keywords internal
NULL

convert_sas_impl <- function(input, output, recursive, flatten, overwrite, sink, compression, io_backend, threads, tmp_dir) .Call("wrap__convert_sas_impl", input, output, recursive, flatten, overwrite, sink, compression, io_backend, threads, tmp_dir, PACKAGE = "fastsasconvert")
