#!/usr/bin/env python3
"""Write an `inst/AUTHORS` listing every vendored Rust crate that ships in a package.

CRAN requires the copyright holders of bundled third-party code to be identifiable
from the package itself, not merely from an upstream registry. The R packages ship
their whole Rust dependency graph as source in `src/rust/vendor.tar.xz`, so that is
115-odd crates to account for.

This reads the vendored tree rather than the lockfile on purpose: the listing then
describes exactly what is in the tarball, and regenerating it is part of the same
step that produces the tarball, so the two cannot drift.

Roughly a quarter of crates omit `authors` — Cargo stopped requiring it, and many
projects dropped it in favour of a git history. For those the crate name and licence
are what can honestly be stated, and the licence text ships alongside in the vendor
tree regardless.
"""

from __future__ import annotations

import os
import re
import sys

# Enough TOML for the three flat, string-valued keys needed here. A real parser
# would be better, but `tomllib` is 3.11+ and this has to run wherever the release
# is cut; the fields are written by cargo and are uniformly simple.
_AUTHORS = re.compile(r"^authors\s*=\s*\[(.*?)\]", re.M | re.S)
_LICENSE = re.compile(r'^license\s*=\s*"([^"]+)"', re.M)
_LICENSE_FILE = re.compile(r'^license-file\s*=\s*"([^"]+)"', re.M)
_VERSION = re.compile(r'^version\s*=\s*"([^"]+)"', re.M)
_STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def _field(pattern: re.Pattern[str], text: str) -> str | None:
    match = pattern.search(text)
    return match.group(1) if match else None


def crate_entry(crate_dir: str) -> tuple[str, str, str] | None:
    manifest = os.path.join(crate_dir, "Cargo.toml")
    if not os.path.isfile(manifest):
        return None
    with open(manifest, encoding="utf-8", errors="replace") as handle:
        text = handle.read()

    version = _field(_VERSION, text) or "?"
    licence = _field(_LICENSE, text)
    if licence is None:
        licence_file = _field(_LICENSE_FILE, text)
        licence = f"see {licence_file}" if licence_file else "see crate sources"
    # Cargo writes SPDX, but a few crates still use the pre-SPDX slash form.
    licence = licence.replace("/", " OR ")

    raw = _field(_AUTHORS, text)
    authors = [
        a.replace('\\"', '"') for a in _STRING.findall(raw)
    ] if raw else []

    name = os.path.basename(crate_dir)
    who = "; ".join(authors) if authors else "(no authors field; see crate sources)"
    return (f"{name} {version}", licence, who)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <vendor-directory> <package-name>", file=sys.stderr)
        return 2
    root, package = sys.argv[1], sys.argv[2]
    if not os.path.isdir(root):
        print(f"not a directory: {root}", file=sys.stderr)
        return 1

    entries = []
    for name in sorted(os.listdir(root), key=str.lower):
        entry = crate_entry(os.path.join(root, name))
        if entry is not None:
            entries.append(entry)

    out = sys.stdout
    title = f"Copyright holders of the Rust code bundled with {package}"
    out.write(
        f"{title}\n"
        f"{'=' * len(title)}\n\n"
        "The R code in this package is copyright Tobias Kragholm, under the licence\n"
        "stated in DESCRIPTION.\n\n"
        "The package additionally bundles the Rust crates listed below, as source, in\n"
        "src/rust/vendor.tar.xz. Each is redistributed under its own licence; the full\n"
        "licence text of every crate ships inside that archive, in the crate's own\n"
        "directory. Where a crate states no authors, cargo no longer requires the field\n"
        "and upstream has not set it.\n\n"
        "This file is generated by scripts/vendor-authors.py from the vendored tree, so\n"
        "that it describes exactly what the tarball contains.\n\n"
        f"{len(entries)} crates.\n\n"
    )
    for crate, licence, who in entries:
        out.write(f"{crate}\n  Licence: {licence}\n  Authors: {who}\n\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
