[package]
name = "sas7bdat-profiler"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = { workspace = true }
mimalloc = { workspace = true }
rayon = { workspace = true }
sas7bdat-simd = { path = "../sas7bdat-simd" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true }
